trabalhos-django/trabalho05/fornecedores/urls.py
from django.urls import path
from fornecedores import views

urlpatterns = [
    path('', views.index_fornecedores, name='index_fornecedores'),
    path('lista_fornecedores/', views.lista_fornecedores, name='lista_fornecedores'),
    path('cadastra_fornecedores/', views.cadastra_fornecedores, name='cadastra_fornecedores'),
    path('exibe_fornecedor/<int:id>/', views.exibe_fornecedor, name='exibe_fornecedor'),
    path('edita_fornecedor/<int:id>/', views.edita_fornecedor, name='edita_fornecedor'),
    path('remove_fornecedor/', views.remove_fornecedor, name='remove_fornecedor'),
]

trabalhos-django/trabalho05/produto/urls.py
from django.urls import path
from produto import views

app_name = 'produto'

urlpatterns = [
    path('', views.index, name='index')
]

trabalhos-django/trabalho05/projeto/urls.py
from django.contrib import admin
from django.urls import path, include

from projeto import views

urlpatterns = [
    path('', views.index, name="index"),
    path('sobre-nos/', views.sobre, name="sobre"),
    path('contato/', views.contato, name="contato"),
    path('loja-alcantara/', views.loja_alcantara, name="loja-alcantara"),
    path('produto/', include('produto.urls')),
    path('fornecedores/', include('fornecedores.urls')),
    path('admin/', admin.site.urls),
]

trabalhos-django/trabalho05/categoria/models.py
from django.db import models

class Categoria(models.Model):
    nome = models.CharField(max_length=100, db_index=True, unique=True)
    slug = models.SlugField(max_length=70)

    class Meta:
        db_table='categoria'
        ordering = ('nome',)

    def __str__(self):
        return self.nome

trabalhos-django/trabalho05/fornecedores/models.py
from django.db import models

class Fornecedores(models.Model):
    nome = models.CharField(max_length=100, db_index=True, unique=True)
    endereco = models.CharField(max_length=100, db_index=True)
    telefone = models.IntegerField(max_length=11, db_index=True)
    cnpj = models.IntegerField(max_length=14, db_index=True)

    class Meta:
        db_table = 'fornecedores'
        ordering = ('nome',)

    def __str__(self):
        return self.nome

trabalhos-django/trabalho05/produto/models.py
from django.db import models
from categoria.models import Categoria

class Produto(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING)
    nome = models.CharField(max_length=150, db_index=True, unique=True)
    slug = models.CharField(max_length=150)
    imagem = models.CharField(max_length=100, blank=True)
    qtd_estoque = models.IntegerField(default=0)
    preco = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    disponivel = models.BooleanField(default=False)

    class Meta:
        db_table = 'produto'

    def __str__(self):
        return self.nome

trabalhos-django/trabalho05/fornecedores/forms.py
from django import forms
from django.core.exceptions import ValidationError

from fornecedores.models import Fornecedores
#Importante, instalar localflavor: pip install django-localflavor
from localflavor.br.forms import BRCNPJField


class PesquisaFornecedorForm(forms.Form):
    nome = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlenght': '100'}),
        required=False
    )

class FornecedorForm(forms.ModelForm):
    class Meta:
        model = Fornecedores
        fields = ('nome', 'endereco', 'telefone', 'cnpj')

    nome = forms.CharField(
        error_messages={'required': 'Campo Obrigatório', 'unique': 'Nome de Fornecedor Duplicado'},
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlenght': '100'})
    )
    endereco = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlenght': '100'})
    )
    telefone = forms.IntegerField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm'})
    )
    cnpj = BRCNPJField(
        error_messages={'required': 'Campo Obrigatório',
                        'unique': 'CNPJ Duplicado',
                        'invalid': 'Digite um CNPJ Válido',
                        'max_digits': 'O CNPJ deve ter 14 dígitos'},
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm'})
    )
    def clean_telefone(self):
        tel = self.cleaned_data['telefone']
        if tel > 99999999999:
            raise ValidationError("O numero de telefone deve possuir entre 10 e 11 digitos, lembre-se de colocar o DDD")
        if tel < 1000000000:
            raise ValidationError("O numero de telefone deve possuir entre 10 e 11 digitos, lembre-se de colocar o DDD")

        # É preciso retornar o valor recuperado de cleaned_data,
        # mesmo que ele não tenha sido alterado.
        return tel

trabalhos-django/trabalho05/categoria/views.py
from django.shortcuts import render

# Create your views here.

trabalhos-django/trabalho05/fornecedores/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from fornecedores.forms import PesquisaFornecedorForm, FornecedorForm
from fornecedores.models import Fornecedores

def index_fornecedores(request):
    return render(request, 'fornecedores/index.html')

def lista_fornecedores(request):
    form = PesquisaFornecedorForm(request.GET)
    if form.is_valid():
        nome = form.cleaned_data['nome']
        lista_de_fornecedores = Fornecedores.objects.filter(nome__icontains=nome).order_by('nome')
        paginator = Paginator(lista_de_fornecedores, 5)
        pagina = request.GET.get('pagina')
        page_obj = paginator.get_page(pagina)
        return render(request, 'fornecedores/pesquisa_fornecedores.html', {'fornecedores': page_obj, 'form': form, 'nome': nome})
    else:
        raise ValueError('Ocorreu um erro inesperado ao tentar recuperar um Fornecedor.')

def cadastra_fornecedores(request):

    if request.POST:
        fornecedor_id = request.session.get('fornecedor_id')
        if(fornecedor_id):
            fornecedor = get_object_or_404(Fornecedores, pk=fornecedor_id)
            fornecedores_form = FornecedorForm(request.POST, instance=fornecedor)
        else:
            fornecedores_form = FornecedorForm(request.POST)

        if fornecedores_form.is_valid():
            fornecedor = fornecedores_form.save(commit=False)
            fornecedor.save()
            if (fornecedor_id):
                messages.add_message(request, messages.INFO, 'Fornecedor Atualizado com Sucesso!')
                del request.session['fornecedor_id']
            else:
                messages.add_message(request, messages.INFO, 'Fornecedor Cadastrado com Sucesso!')
            return render(request, 'fornecedores/exibe_fornecedor.html', {'fornecedor': fornecedor})
    else:
        try:
            del request.session['fornecedor_id']
        except KeyError:
            pass
        fornecedores_form = FornecedorForm()

    return render(request, 'fornecedores/cadastra_fornecedores.html', {'form': fornecedores_form})

def exibe_fornecedor(request, id):
    fornecedor = get_object_or_404(Fornecedores, pk=id)
    request.session['fornecedor_id_del'] = id
    return render(request, 'fornecedores/exibe_fornecedor.html', {'fornecedor': fornecedor})

def edita_fornecedor(request, id):
    fornecedor = get_object_or_404(Fornecedores, pk=id)
    fornecedor_form = FornecedorForm(instance=fornecedor)
    request.session['fornecedor_id'] = id
    return render(request, 'fornecedores/cadastra_fornecedores.html', {'form': fornecedor_form})

def remove_fornecedor(request):
    fornecedor_id = request.session.get('fornecedor_id_del')
    fornecedor = get_object_or_404(Fornecedores, id=fornecedor_id)
    fornecedor.delete()
    del request.session['fornecedor_id_del']
    messages.add_message(request, messages.INFO, 'Fornecedor removido com Sucesso.')
    return render(request, 'fornecedores/exibe_fornecedor.html', {'fornecedor': fornecedor})

trabalhos-django/trabalho05/produto/views.py
from django.shortcuts import render

def index(request):
    frase="Index de produto"
    return render(request, 'produto/index.html', {'frase': frase})

trabalhos-django/trabalho05/projeto/views.py
from django.shortcuts import render

from produto.models import Produto


def index(request):
    lista_de_produtos = Produto.objects.all().order_by('nome')
    return render(request, 'index.html', {'produtos': lista_de_produtos})

def sobre(request):
    return render(request, 'sobre.html')

def contato(request):
    return render(request, 'contato.html')

def loja_alcantara(request):
    return render(request, 'loja-alcantara.html')

def lista_produto(request):
    lista_de_produtos = Produto.objects.all().order_by('nome')

trabalhos-django/trabalho05/fornecedores/templates/fornecedores/cadastra_fornecedores.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
    {% if 'fornecedor_id' in request.session %}
        Editando Fornecedor
    {% else %}
        Cadastro de Fornecedor
    {% endif %}
{% endblock %}

{% block corpo %}
    <div class="titulopagina containerundermenu mb-5" style="background-image: url({% static 'imagens/bg-sobre.jpg'%});">
        <h1 class="textotitulo">
            {% if 'fornecedor_id' in request.session %}
                Editar um Fornecedor
            {% else %}
                Cadastrar de Fornecedor
            {% endif %}
        </h1>
    </div>

    <div style="width:100%; max-width:800px; min-height: 300px; margin: 0 auto;">
        <form action="{% url 'cadastra_fornecedores' %}" method="POST" class="pb-4" novalidate>
            <div class="row mb-2">
                <div class="col-md-4">
                    <label for="id_nome">Nome</label>
                </div>
                <div class="col-md-8">
                    {{ form.nome }}
                    {% if form.nome.errors %}
                        <div class="alert alert-danger mb-0" role="alert" style="padding-top:2px; padding-bottom: 2px;">
                            {% for error in form.nome.errors %}
                                <small>{{ error }}</small>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-md-4">
                    <label for="id_endereco">Endereço</label>
                </div>
                <div class="col-md-8">
                    {{ form.endereco }}
                    {% if form.endereco.errors %}
                        <div class="alert alert-danger mb-0" role="alert" style="padding-top:2px; padding-bottom: 2px;">
                            {% for error in form.endereco.errors %}
                                <small>{{ error }}</small>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-md-4">
                    <label for="id_telefone">Telefone</label>
                </div>
                <div class="col-md-8">
                    {{ form.telefone }}
                    {% if form.telefone.errors %}
                        <div class="alert alert-danger mb-0" role="alert" style="padding-top:2px; padding-bottom: 2px;">
                            {% for error in form.telefone.errors %}
                                <small>{{ error }}</small>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-md-4">
                    <label for="id_cnpj">CNPJ</label>
                </div>
                <div class="col-md-8">
                    {{ form.cnpj }}
                    {% if form.cnpj.errors %}
                        <div class="alert alert-danger mb-0" role="alert" style="padding-top:2px; padding-bottom: 2px;">
                            {% for error in form.cnpj.errors %}
                                <small>{{ error }}</small>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="mt-2">
                {% csrf_token %}
                <button id="botao" type='submit' class='btn btn-danger'>
                    <div class="d-flex align-items-center">
                        {% if 'fornecedor_id' in request.session %}
                            <i class="fas fa-save mr-2"></i> <div style="padding-left: 4px;"> Alterar</div>
                        {% else %}
                            <i class="fas fa-save mr-2"></i> <div style="padding-left: 4px;"> Cadastrar</div>
                        {% endif %}
                    </div>
                </button>
            </div>
        </form>

    </div>

{% endblock %}

trabalhos-django/trabalho05/fornecedores/templates/fornecedores/exibe_fornecedor.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
    Exibir Fornecedor
{% endblock %}

{% block corpo %}
    <div class="titulopagina containerundermenu mb-5" style="background-image: url({% static 'imagens/bg-sobre.jpg'%});">
        <h1 class="textotitulo">Exibe um fornecedor</h1>
    </div>

    <div style="width:100%; max-width:800px; min-height: 300px; margin: 0 auto;">
        {% if messages %}
            {% for message in messages %}
                <li style="padding-bottom: 7px; padding-top: 7px" class="list-group-item list-group-item-info">
                {{ message }}
                </li>
            {% endfor %}
        {% endif %}
        <div class="row">
            <h3><b>Nome:</b>{{ fornecedor.nome }}</h3>
            <p><b>Endereço:</b>{{ fornecedor.endereco }}</p>
            <p><b>Telefone:</b>{{ fornecedor.telefone }}</p>
            <p><b>CNPJ:</b>{{ fornecedor.cnpj }}</p>
        </div>
    </div>
    {%  if fornecedor.id %}
    <div style="width:100%; max-width:800px; min-height: 200px; margin: 10px auto;">
           <div class="row">
               <div class="col-md-6">
                   <a href="{% url 'edita_fornecedor' fornecedor.id %}" class='btn btn-danger w-100 text-center'>
                        <div class="d-flex align-items-center justify-content-center">
                            <i class="fas fa-edit"></i><div style="padding-left: 4px;">Editar Fornecedor</div>
                        </div>
                    </a>
               </div>
               <div class="col-md-6">
                   <form action="{% url 'remove_fornecedor' %}" method="POST">
                       {% csrf_token %}
                       <button type="submit" class='btn btn-danger w-100 text-center'>
                            <div class="d-flex align-items-center justify-content-center">
                                    <i class="fas fa-trash-alt"></i><div style="padding-left: 4px;">Remover Fornecedor</div>
                            </div>
                       </button>
                   </form>
               </div>
           </div>
    </div>
    {% endif %}

{% endblock %}

trabalhos-django/trabalho05/fornecedores/templates/fornecedores/index.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
    Controle de Fornecedores
{% endblock %}

{% block corpo %}
    <div class="titulopagina containerundermenu mb-5" style="background-image: url({% static 'imagens/bg-sobre.jpg'%});">
        <h1 class="textotitulo">Controle de Fornecedores</h1>
    </div>

    <div style="width:100%; max-width:800px; min-height: 200px; margin: 10px auto;">
        <h4>Pesquise um Fornecedor:</h4>
           <div class="row">
               <div class="col-md-6">
                   <a href="{% url 'lista_fornecedores' %}" class='btn btn-danger w-100 text-center'>
                        <div class="d-flex align-items-center justify-content-center">
                            <i class="fas fa-th-list" ></i><div style="padding-left: 4px;">Listar Fornecedores</div>
                        </div>
                    </a>
               </div>
               <div class="col-md-6">
                   <a href="{% url 'cadastra_fornecedores' %}" class='btn btn-danger w-100 text-center'>
                        <div class="d-flex align-items-center justify-content-center">
                            <i class="fas fa-plus-circle mr-2"></i><div style="padding-left: 4px;"> Cadastrar Fornecedor</div>
                        </div>
                    </a>
               </div>
           </div>
    </div>

{% endblock %}

trabalhos-django/trabalho05/fornecedores/templates/fornecedores/pesquisa_fornecedores.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
    Pesquisa de Fornecedores
{% endblock %}

{% block corpo %}
    <div class="titulopagina containerundermenu mb-5" style="background-image: url({% static 'imagens/bg-sobre.jpg'%});">
        <h1 class="textotitulo">Lista de Fornecedores</h1>
    </div>

    <div style="width:100%; max-width:800px; margin: 0 auto;">
    <h4>Pesquise um Fornecedor:</h4>
    <form action="" method ='GET' class="mb-4">
        <div class='form-group row' style='margin-bottom: 10px;'>
            <label for='id_nome' class='col-lg-2 col-form-label font-weight-bold text-right pr-2'>
                Nome
            </label>
            <div class='col-lg-8'>
                {{ form.nome }}
            </div>
            <div class="col-lg-2">
                <button type='submit' class='btn btn-danger'>
                    <div class="d-flex align-items-center">
                        <i class="fas fa-search mr-2"></i> Pesquisar
                    </div>
                </button>
            </div>
        </div>
    </form>
    </div>

    <div style="width:100%; max-width:1200px; min-height: 300px; margin: 0 auto;">
        {% if fornecedores %}
            <table style="width:100%" class="table table-striped table-sm table-bordered table-responsive mb-4">
                <thead>
                    <tr>
                        <th class="text-center">Nome</th>
                        <th class="text-center">Endereço</th>
                        <th class="text-center">Telefone</th>
                        <th class="text-center">CNPJ</th>
                    </tr>
                </thead>
                <tbody>
                    {% for fornecedor in fornecedores %}
                        <tr>
                            <td class="text-center align-middle">
                                <a href="{% url 'exibe_fornecedor' fornecedor.id %}">
                                {{fornecedor.nome}}
                                </a>
                            </td>
                            <td class="text-center align-middle">
                                {{fornecedor.endereco}}
                            </td>
                            <td class="text-center align-middle">
                                {{fornecedor.telefone}}
                            </td>
                            <td class="text-center align-middle">
                                {{fornecedor.cnpj}}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div style='font-size: 14px; margin-bottom: 28px'>
                {% if fornecedores.has_other_pages %}
                    <ul class='pagination' id="paginacao">
                        {% if fornecedores.has_previous %}
                            <li class='page-item'><a class='page-link' href='?pagina={{ fornecedores.previous_page_number }}&nome={{ nome }}'>Anterior</a></li>
                        {% else %}
                            <li class='page-item disabled'><a class='page-link' href='#' tabindex='-1'>Anterior</a></li>
                        {% endif %}
                        {% for i in fornecedores.paginator.page_range %}
                            {% if fornecedores.number == i %}
                                <li class='page-item active'><a class='page-link' href='#'>{{ i }} </a></li>
                            {% else %}
                                <li class='page-item'><a class='page-link' href='?pagina={{ i }}&nome={{ nome }}'>{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if fornecedores.has_next %}
                            <li class='page-item'><a class='page-link' href='?pagina={{ fornecedores.next_page_number }}&nome={{ nome }}'>Próxima</a></li>
                        {% else %}
                            <li class='page-item disabled'><a class='page-link' href='#' tabindex='-1'>Próxima</a></li>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
        {% else %}
        {% endif %}

    </div>

{% endblock %}

trabalhos-django/trabalho05/produto/templates/produto/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Produto</title>
</head>
<body>
    {{ frase }}
    <img src="{% static 'imagens/produtos/abacaxi-perola.jpg' %}" />
</body>
</html>

trabalhos-django/trabalho05/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--Arquivos de Estilo - ESTATICOS-->
    <link href="{% static 'css/estilo.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
    <!--FONT AWESOME-->
    <script src="https://kit.fontawesome.com/aeda5607de.js" crossorigin="anonymous"></script>
    <!--Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <!--TITULO-->
    <title>
        {% block titulo %}
            Portugas - Hortifruti
        {% endblock %}
    </title>
</head>
<body>
    {% block navbar %}
        <!--NAVBAR-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light navegacao fixed-top">
            <div class="container bg-light">
              	<a class="navbar-brand" href="{% url "index" %}"><img src="{% static 'imagens/logo.png' %}" class="logonav"></a>
              	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                	<span class="navbar-toggler-icon"></span>
              	</button>
              	<div class="collapse navbar-collapse" id="navbarSupportedContent">
                	<ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  		<li class="nav-item">
                    		<a class="nav-link" href="/">Início</a>
                  		</li>
                 		<li class="nav-item">
                    		<a class="nav-link" href="{% url "sobre" %}">Sobre Nós</a>
                  		</li>
                  		<li class="nav-item dropdown">
                    		<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      			Departamentos
                    		</a>
                    		<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      			<li><a class="dropdown-item" href="#">Hortifruti</a></li>
                      			<li><a class="dropdown-item" href="#">Mercearia</a></li>
                    		</ul>
                  		</li>
                  		<li class="nav-item">
                    		<a class="nav-link" href="{% url "contato" %}">Contato</a>
                  		</li>
                        <li class="nav-item dropdown">
                    		<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      			Administração
                    		</a>
                    		<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      			<li><a class="dropdown-item" href="{% url 'index_fornecedores' %}">Fornecedores</a></li>
                    		</ul>
                  		</li>
                	</ul>
                	<form class="d-flex">
                  		<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  		<button class="btn btn-outline-success" type="submit">Search</button>
                	</form>
              	</div>
            </div>
        </nav>
    {% endblock %}

    {% block corpo %}
    {% endblock %}

    {% block rodape %}
        <div class="rodape">
			<div class="container">
				<div class="row">
					<hr>
					<div class="col-md-3 align-self-center"><img class="w-100" style="max-width:100px" src="{% static 'imagens/logo.png' %}" /></div>
					<div class="col-md-6 align-self-center text-center">
						<div class="btn-group" role="group" aria-label="Basic example">
						<a type="button" href="{% url "sobre" %}" class="btn btn-link linkrodape" >Sobre Nós</a>
						<a type="button" href="{% url "loja-alcantara" %}" class="btn btn-link linkrodape">Nossa Loja</a>
						<a type="button" class="btn btn-link linkrodape" data-bs-toggle="modal" data-bs-target="#modalHorarios">Horário de Funcionamento</a>
						<a type="button" class="btn btn-link linkrodape" data-bs-toggle="offcanvas" data-bs-target="#offcanvasBottom" aria-controls="offcanvasBottom"	>Siga-nos</a>

					</div>
					</div>
					<div class="col-md-3 align-self-center">
						<div style="text-align: right;">
							©2021 - Todos os Direitos Reservados
						</div>
					</div>
				</div>
			</div>
        </div>
    {% endblock %}

    <div class="offcanvas offcanvas-bottom" tabindex="-1" id="offcanvasBottom" aria-labelledby="offcanvasBottomLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasBottomLabel">Siga-nos nas redes sociais</h5>
            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body small text-center">
            <p>Estamos nas redes sociais, e em nossos canais oficiais estaremos realizando promoções e descontos exclusivos, siga-nos para ficar por dentro de tudo!</p>
            <div class="btn-group">
                <a href="https://www.facebook.com/hortifrutiportugas" target="_blank" class="btn btn-primary"><i class="fab fa-facebook-square"></i> Facebook</a>
                <a href="https://www.instagram.com/portugashortifruti/" target="blank" class="btn btn-primary"><i class="fab fa-instagram"></i> Instagram</a>
                <a href="#" class="btn btn-primary" onclick="alert('Em Breve')">Whatsapp</a>
            </div>
        </div>
    </div>
    <!--Scripts-->
    <script src="{% static '/node_modules/jquery/dist/jquery.min.js'%}"></script>
    <script src="{% static '/js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

<!-- Modal Horarios -->
<div class="modal fade" id="modalHorarios" tabindex="-1" aria-labelledby="modalHorariosLabel" aria-hidden="true">
	<div class="modal-dialog">
	  <div class="modal-content">
		<div class="modal-header">
		  <h5 class="modal-title" id="modalHorariosLabel">Horarios de Funcionamento</h5>
		  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
		</div>
		<div class="modal-body">
			<ul class="list-group">
				<li class="list-group-item"><b>Segunda-feira:</b> 7:00hs as 19:00hs</li>
				<li class="list-group-item"><b>Terça-feira:</b> 7:00hs as 19:00hs</li>
				<li class="list-group-item"><b>Quarta-feira:</b> 7:00hs as 19:00hs</li>
				<li class="list-group-item"><b>Quinta-feira:</b> 7:00hs as 19:00hs<br></li>
				<li class="list-group-item"><b>Sexta-feira:</b> 7:00hs as 19:00hs<br></li>
				<li class="list-group-item"><b>Sábado:</b> 7:00hs as 19:00hs<br></li>
				<li class="list-group-item"><b>Domingo:</b> 7:00hs as 12:00hs<br></li>
			</ul>
		</div>
		<div class="modal-footer">
		  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
		</div>
	  </div>
	</div>
</div>

trabalhos-django/trabalho05/templates/contato.html
{%  extends "base.html" %}
{% load static %}

{% block title %}
    Contato - Portugas Hortifrutti
{% endblock %}

{% block corpo %}

    <div class="titulopagina containerundermenu" style="background-image: url({% static 'imagens/bg-contato.jpg' %});">
        <h1 class="textotitulo">Contato</h1>
    </div>

    <div class="container">
        <div class="row">
            <section class="col-xs-12">

                <br/>
                <h3 class="text-center">Entre em contato conosco:</h3>
                <br/>
                <p class="text-center">Deixe a sua mensagem, responderemos assim que possível!</p>

                <form class="containercontent pb-5">

                    <div class="form-group">
                        <label class="col12 control-label" for="nome">Nome</label>
                        <div class="col-12">
                            <input class="form-control" type="text" id="nome" placeholder="Nome">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-12 control-label" for="email">Email</label>
                        <div class="col-12">
                            <input class="form-control" type="email" id="email" placeholder="Email">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-12 control-label" for="mensagem">Mensagem</label>
                            <div class="col-12">
                            <textarea class="form-control" id="mensagem"></textarea>
                        </div>
                    </div>

                    <div class="form-group mt-3">
                        <div class="col-sm-8 col-sm-offset-2">
                            <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-save"></span> Enviar</button>
                        </div>
                    </div>
                </form>
            </section>
        </div><!-- row -->
    </div><!-- content container -->

{% endblock %}