trabalhos-django/trabalho06 - Copia/produto/urls.py
from django.urls import path
from produto import views

app_name = 'produto'

urlpatterns = [
    path('', views.index, name='index'),
    path('cadastra_produto/', views.cadastra_produto, name='cadastra_produto'),
    path('lista_produtos/', views.lista_produtos, name='lista_produtos'),
]

trabalhos-django/trabalho06 - Copia/projeto/urls.py
from django.contrib import admin
from django.urls import path, include

from projeto import views

urlpatterns = [
    path('', views.index, name="index"),
    path('produto/', include('produto.urls')),
    path('admin/', admin.site.urls),
]

trabalhos-django/trabalho06 - Copia/categoria/models.py
from django.db import models

class Categoria(models.Model):
    nome = models.CharField(max_length=100, db_index=True, unique=True)
    slug = models.SlugField(max_length=70)

    class Meta:
        db_table='categoria'
        ordering = ('nome',)

    def __str__(self):
        return self.nome

trabalhos-django/trabalho06 - Copia/produto/models.py
from django.db import models
from categoria.models import Categoria

class Produto(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING)
    nome = models.CharField(max_length=150, db_index=True)
    qtd = models.IntegerField(default=0)
    preco = models.DecimalField(max_digits=8, decimal_places=2, default=0)

    class Meta:
        db_table = 'produto2'

    def __str__(self):
        return self.nome

trabalhos-django/trabalho06 - Copia/produto/forms.py
from django import forms
from django.core.exceptions import ValidationError

from produto.models import Produto
from categoria.models import Categoria

class PesquisaFornecedorForm(forms.Form):
    nome = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlenght': '100'}),
        required=False
    )

class CadastraProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = ('nome', 'categoria', 'qtd', 'preco')

    nome = forms.CharField(
        error_messages={'required': 'Campo Obrigatório'},
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlenght': '100'})
    )
    categoria = forms.ModelChoiceField(
        error_messages={'required': 'Campo Obrigatório'},
        queryset=Categoria.objects.all().order_by('nome'),
        empty_label="---Selecione uma Categoria---",
        widget=forms.Select(attrs={'class': 'form-control form-control-sm'})
    )
    qtd = forms.IntegerField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm'})
    )
    preco = forms.DecimalField(
        localize=True,
        min_value=0,
        error_messages={'required': 'Campo Obrigatório',
                        'invalid': 'Preço Inválido',
                        'min_value': 'O preço deve ser maior ou igual a zero',
                        'max_decimal_places': 'mais de 2 digitos decimais',
                        'max_digits': 'O número pode ter até 8 digitos no total',
                        'max_whole_digits': 'Na parte inteira, o número deve ter até 6 dígitos no total'
                        },
        widget=forms.TextInput(attrs={'class': "form-control form-control-sm",
                                      'onkeypress': 'return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44'})
    )

trabalhos-django/trabalho06 - Copia/categoria/views.py
from django.shortcuts import render

# Create your views here.

trabalhos-django/trabalho06 - Copia/produto/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404

from produto.forms import CadastraProdutoForm
from produto.models import Produto


def index(request):
    frase="Index de produto"
    return render(request, 'produto/index.html', {'frase': frase})

def cadastra_produto(request):
    if request.POST:
        produto_form = CadastraProdutoForm(request.POST)
        if produto_form.is_valid():
            produto = produto_form.save(commit=False)
            produto.save()
            messages.add_message(request, messages.INFO, 'Fornecedor Cadastrado com Sucesso!')

            return render(request, 'fornecedores/exibe_fornecedor.html', {'fornecedor': fornecedor})
    produto_form = CadastraProdutoForm()
    return render(request, 'produto/cadastra_produto.html', {'form': produto_form})

def lista_produtos(request):

    return render(request, 'produto/lista_produtos.html')

trabalhos-django/trabalho06 - Copia/projeto/views.py
from django.shortcuts import render

from produto.models import Produto


def index(request):
    lista_de_produtos = Produto.objects.all().order_by('nome')
    return render(request, 'index.html', {'produtos': lista_de_produtos})

def sobre(request):
    return render(request, 'sobre.html')

def contato(request):
    return render(request, 'contato.html')

def loja_alcantara(request):
    return render(request, 'loja-alcantara.html')

def lista_produto(request):
    lista_de_produtos = Produto.objects.all().order_by('nome')

trabalhos-django/trabalho06 - Copia/produto/templates/produto/cadastra_produto.html
    <div style="width:100%; max-width:800px; min-height: 300px; margin: 0 auto;">
        <form id="post-form" method="POST" class="pb-4">
            <div class="row mb-2">
                <div class="col-md-4">
                    <label for="id_nome">Nome</label>
                </div>
                <div class="col-md-8">
                    {{ form.nome }}
                    {% if form.nome.errors %}
                        <div class="alert alert-danger mb-0" role="alert" style="padding-top:2px; padding-bottom: 2px;">
                            {% for error in form.nome.errors %}
                                <small>{{ error }}</small>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-md-4">
                    <label for="id_endereco">Categoria</label>
                </div>
                <div class="col-md-8">
                    {{ form.categoria }}
                    {% if form.categoria.errors %}
                        <div class="alert alert-danger mb-0" role="alert" style="padding-top:2px; padding-bottom: 2px;">
                            {% for error in form.categoria.errors %}
                                <small>{{ error }}</small>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-md-4">
                    <label for="id_telefone">Quantidade</label>
                </div>
                <div class="col-md-8">
                    {{ form.qtd }}
                    {% if form.qtd.errors %}
                        <div class="alert alert-danger mb-0" role="alert" style="padding-top:2px; padding-bottom: 2px;">
                            {% for error in form.qtd.errors %}
                                <small>{{ error }}</small>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-md-4">
                    <label for="id_cnpj">Preço</label>
                </div>
                <div class="col-md-8">
                    {{ form.preco }}
                    {% if form.preco.errors %}
                        <div class="alert alert-danger mb-0" role="alert" style="padding-top:2px; padding-bottom: 2px;">
                            {% for error in form.preco.errors %}
                                <small>{{ error }}</small>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="mt-2">
                {% csrf_token %}
                <button id="botao" class='btn btn-danger enviar'>
                    <div class="d-flex align-items-center">
                        {% if 'fornecedor_id' in request.session %}
                            <i class="fas fa-save mr-2"></i> <div style="padding-left: 4px;"> Alterar</div>
                        {% else %}
                            <i class="fas fa-save mr-2"></i> <div style="padding-left: 4px;"> Cadastrar</div>
                        {% endif %}
                    </div>
                </button>
            </div>
        </form>

    </div>

trabalhos-django/trabalho06 - Copia/produto/templates/produto/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Produto</title>
</head>
<body>
    {{ frase }}
    <img src="{% static 'imagens/produtos/abacaxi-perola.jpg' %}" />
</body>
</html>

trabalhos-django/trabalho06 - Copia/produto/templates/produto/lista_produtos.html
<table style="width:100%">
    <thead>
        <tr>
            <td style="border:1px solid #ccc">Nome</td>
            <td style="border:1px solid #ccc">Categoria</td>
            <td style="border:1px solid #ccc">Qtd</td>
            <td style="border:1px solid #ccc">Valor</td>
        </tr>
    </thead>
    <tbody id="conteudotabela">

    </tbody>
    <tfoot>
        <tr>
            <td style=""></td>
            <td style=""></td>
            <td style="border:1px solid #ccc">Total</td>
            <td style="border:1px solid #ccc">0</td>
        </tr>
    </tfoot>

</table>

trabalhos-django/trabalho06 - Copia/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--Arquivos de Estilo - ESTATICOS-->
    <link href="{% static 'css/estilo.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
    <!--FONT AWESOME-->
    <script src="https://kit.fontawesome.com/aeda5607de.js" crossorigin="anonymous"></script>
    <!--Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <!--TITULO-->
    <title>
        {% block titulo %}
            Portugas - Hortifruti
        {% endblock %}
    </title>
</head>
<body>
    {% block navbar %}
        <!--NAVBAR-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light navegacao fixed-top">
            <div class="container bg-light">
              	<a class="navbar-brand" href="{% url "index" %}">Trabalho06</a>
              	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                	<span class="navbar-toggler-icon"></span>
              	</button>
              	<div class="collapse navbar-collapse" id="navbarSupportedContent">
                	<ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  		<li class="nav-item">
                    		<a class="nav-link" href="/">Início</a>
                  		</li>
                	</ul>
              	</div>
            </div>
        </nav>
    {% endblock %}

    {% block corpo %}
    {% endblock %}

    {% block rodape %}
        <div class="rodape">
			<div class="container">
				<div class="row">
					<hr>
					<div class="col-md-3 align-self-center"></div>
					<div class="col-md-6 align-self-center text-center">
						<div class="btn-group" role="group" aria-label="Basic example">
						<a type="button" class="btn btn-link linkrodape" data-bs-toggle="modal" data-bs-target="#modalHorarios">Horário de Funcionamento</a>
						<a type="button" class="btn btn-link linkrodape" data-bs-toggle="offcanvas" data-bs-target="#offcanvasBottom" aria-controls="offcanvasBottom"	>Siga-nos</a>

					</div>
					</div>
					<div class="col-md-3 align-self-center">
						<div style="text-align: right;">
							©2021 - Todos os Direitos Reservados
						</div>
					</div>
				</div>
			</div>
        </div>
    {% endblock %}

    <div class="offcanvas offcanvas-bottom" tabindex="-1" id="offcanvasBottom" aria-labelledby="offcanvasBottomLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasBottomLabel">Siga-nos nas redes sociais</h5>
            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body small text-center">
            <p>Estamos nas redes sociais, e em nossos canais oficiais estaremos realizando promoções e descontos exclusivos, siga-nos para ficar por dentro de tudo!</p>
            <div class="btn-group">
                <a href="https://www.facebook.com/hortifrutiportugas" target="_blank" class="btn btn-primary"><i class="fab fa-facebook-square"></i> Facebook</a>
                <a href="https://www.instagram.com/portugashortifruti/" target="blank" class="btn btn-primary"><i class="fab fa-instagram"></i> Instagram</a>
                <a href="#" class="btn btn-primary" onclick="alert('Em Breve')">Whatsapp</a>
            </div>
        </div>
    </div>
    <!--Scripts-->
    <script src="{% static '/node_modules/jquery/dist/jquery.min.js'%}"></script>
    <script src="{% static '/js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script>
        $(document).ready(function(){

            {% block domready %}

            {% endblock %}

            $("#lista-produtos").on("click", "input.comprar", function(){
                this.blur()
                let botao_comprar = this
                let form = $(botao_comprar).prev()
                form.find("input[name='quantidade']").val(1)
                let url = form.attr('action')
                let formData = form.serializeArray()
                $.post(url, formData, function(resposta) {
                    $(botao_comprar).fadeTo('fast', 0.3, function() {
                        $(botao_comprar).hide()
                        form.show()
                        if (resposta.quantidade === 1)
                            $("#total-1").text(resposta.quantidade + " item - " + resposta.preco_carrinho)
                        else
                            $("#total-1").text(resposta.quantidade + " itens - " + resposta.preco_carrinho)
                        $("#total-2").text(resposta.preco_carrinho)
                    })
                })
            })

            $("#lista-produtos").on("click", "input.mais", function(){
                this.blur()
                var input = $(this).parent().prev()
                var num = +input.val() + 1
                if (num < 100) {
                    input.val(num)
                    let form = $(this).parent().parent().parent()
                    let url = form.attr('action')
                    let formData = form.serializeArray()
                    $.post(url, formData, function(resposta) {
                        if (resposta.quantidade === 1)
                            $("#total-1").text(resposta.quantidade + " item - " + resposta.preco_carrinho)
                        else
                            $("#total-1").text(resposta.quantidade + " itens - " + resposta.preco_carrinho)
                        $("#total-2").text(resposta.preco_carrinho)
                    })
                }
                else {
                    return
                }
            })

            $("#lista-produtos").on("click", "input.menos", function(){
                this.blur()
                let botao_menos = this
                let input = $(botao_menos).parent().next()
                let num = +input.val() - 1
                if (num < 0) {
                    num = 0
                }
                input.val(num)
                let form = $(botao_menos).parent().parent().parent()
                let botao_comprar = form.next()
                let url = form.attr('action')
                let formData = form.serializeArray()
                $.post(url, formData, function(resposta) {
                    if (num == 0) {
                        form.hide()
                        $(botao_comprar).fadeTo('fast', 1)
                    }
                    if (resposta.quantidade === 1)
                        $("#total-1").text(resposta.quantidade + " item - " + resposta.preco_carrinho)
                    else
                        $("#total-1").text(resposta.quantidade + " itens - " + resposta.preco_carrinho)
                    $("#total-2").text(resposta.preco_carrinho)
                })
            })
        });
    </script>
</body>
</html>

<!-- Modal Horarios -->
<div class="modal fade" id="modalHorarios" tabindex="-1" aria-labelledby="modalHorariosLabel" aria-hidden="true">
	<div class="modal-dialog">
	  <div class="modal-content">
		<div class="modal-header">
		  <h5 class="modal-title" id="modalHorariosLabel">Horarios de Funcionamento</h5>
		  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
		</div>
		<div class="modal-body">
			<ul class="list-group">
				<li class="list-group-item"><b>Segunda-feira:</b> 7:00hs as 19:00hs</li>
				<li class="list-group-item"><b>Terça-feira:</b> 7:00hs as 19:00hs</li>
				<li class="list-group-item"><b>Quarta-feira:</b> 7:00hs as 19:00hs</li>
				<li class="list-group-item"><b>Quinta-feira:</b> 7:00hs as 19:00hs<br></li>
				<li class="list-group-item"><b>Sexta-feira:</b> 7:00hs as 19:00hs<br></li>
				<li class="list-group-item"><b>Sábado:</b> 7:00hs as 19:00hs<br></li>
				<li class="list-group-item"><b>Domingo:</b> 7:00hs as 12:00hs<br></li>
			</ul>
		</div>
		<div class="modal-footer">
		  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
		</div>
	  </div>
	</div>
</div>

trabalhos-django/trabalho06 - Copia/templates/contato.html
{%  extends "base.html" %}
{% load static %}

{% block title %}
    Contato - Portugas Hortifrutti
{% endblock %}

{% block corpo %}

    <div class="titulopagina containerundermenu" style="background-image: url({% static 'imagens/bg-contato.jpg' %});">
        <h1 class="textotitulo">Contato</h1>
    </div>

    <div class="container">
        <div class="row">
            <section class="col-xs-12">

                <br/>
                <h3 class="text-center">Entre em contato conosco:</h3>
                <br/>
                <p class="text-center">Deixe a sua mensagem, responderemos assim que possível!</p>

                <form class="containercontent pb-5">

                    <div class="form-group">
                        <label class="col12 control-label" for="nome">Nome</label>
                        <div class="col-12">
                            <input class="form-control" type="text" id="nome" placeholder="Nome">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-12 control-label" for="email">Email</label>
                        <div class="col-12">
                            <input class="form-control" type="email" id="email" placeholder="Email">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-12 control-label" for="mensagem">Mensagem</label>
                            <div class="col-12">
                            <textarea class="form-control" id="mensagem"></textarea>
                        </div>
                    </div>

                    <div class="form-group mt-3">
                        <div class="col-sm-8 col-sm-offset-2">
                            <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-save"></span> Enviar</button>
                        </div>
                    </div>
                </form>
            </section>
        </div><!-- row -->
    </div><!-- content container -->

{% endblock %}

trabalhos-django/trabalho06 - Copia/templates/index.html
{%  extends "base.html" %}
{% load static %}

{% block title %}
    Portugas Hortifrutti - Página Inicial
{% endblock %}

{% block corpo %}
    <div style="padding-top: 100px; width: 100%; max-width: 1000px; margin:0 auto; min-height: 550px">
        <h1>Cadastro de Produtos</h1>
        <br>
        <div id="form">

        </div>
        <br>
        <div id="tabela">

        </div>
        <br><br>
    </div>

{% endblock %}

{% block domready %}
    $.get("{% url 'produto:cadastra_produto' %}", function(resposta){
        $('#form').html(resposta)
    })
    $.get("{% url 'produto:lista_produtos' %}", function(resposta){
        $('#tabela').html(resposta)
    })

    $('#post-form').on('submit', function(event){
        event.preventDefault();
        console.log("form submitted!")  // sanity check
    })
{% endblock %}

trabalhos-django/trabalho06 - Copia/templates/loja-alcantara.html
{%  extends "base.html" %}
{% load static %}

{% block title %}
    Contato - Portugas Hortifrutti
{% endblock %}

{% block corpo %}

    <div class="map-example container" style="padding-top: 120px; padding-bottom: 30px;">
        <div class="row">
            <div class="col-lg-6">
                <div id="map">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3677.5833375531715!2d-43.011790085449064!3d-22.817897985057094!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9990907438fbc9%3A0x656a8d2440adb031!2sR.%20Dr.%20Alfredo%20Backer%2C%20411%20-%20Alcantara%2C%20S%C3%A3o%20Gon%C3%A7alo%20-%20RJ%2C%2024452-001!5e0!3m2!1spt-BR!2sbr!4v1624816637295!5m2!1spt-BR!2sbr" class="w-100" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                </div>
            </div>
            <div class="col-lg-6 align-self-center">
                <div class="heading">
                    <h3>Portuga's Alcântara</h3>
                    <div class="rating">
                        <i class="fa fa-star icon"></i>
                        <i class="fa fa-star icon"></i>
                        <i class="fa fa-star icon"></i>
                        <i class="fa fa-star icon"></i>
                        <i class="fa fa-star icon"></i>
                    </div>
                </div>
                <div class="info">
                    <p><b>Endereço:</b> Rua Dr Alfredo Backer, 411 - Alcântara - São Gonçalo</p>
                    <p>Localizado próximo ao 7° Batalhão e a Academia Alternativa</p>
                </div>
                <div class="gallery">
                    <h4>Fotos</h4>
                    <div class="row">
                        <div class="col-md-4">
                            <img class="img-fluid image" src="{% static 'imagens/portugas1.jpeg' %}">
                        </div>
                        <div class="col-md-4">
                            <img class="img-fluid image" src="{% static 'imagens/portugas2.jpeg' %}">
                        </div>
                        <div class="col-md-4">
                            <img class="img-fluid image" src="{% static 'imagens/portugas3.jpeg' %}">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

trabalhos-django/trabalho06 - Copia/templates/sobre.html
{%  extends "base.html" %}
{% load static %}

{% block title %}
    Sobre Nós - Portugas Hortifrutti
{% endblock %}

{% block corpo %}

    <div class="titulopagina containerundermenu" style="background-image: url({% static 'imagens/bg-sobre.jpg'%});">
        <h1 class="textotitulo">Sobre Nós</h1>
    </div>

    <div class="containercontent pt-5">
        <div class="row">
            <div class="col-md-6 text-justify align-self-center" style="text-align:justify" >
                <p>Uma aventura em Família, assim podemos definir o Portuga's.</p>
                <p>Fundado por 2 irmãos, membros da família Freitas, conhecidos na região como "Portugas", o Portuga's Hortifrutti & Mercearia nasceu de um antigo sonho de investimento. Com a proposta de facilitar moradores da região, fornecendo produtos de qualidade e mantendo um preço justo.</p>
                <p>Nossa intenção é garantir que você seja bem servido em nosso estabelecimento!</p>
                <p>Faça uma visita e conheça nossa loja!</p>
            </div>
            <div class="col-md-6 align-self-center">
                <img src="{% static 'imagens/foto-sobre.png' %}" class="w-100" alt="foto equipe Portuga's">
            </div>
        </div>

        <div class="accordion" id="accordionExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button bg-verde" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Nossos Horários
                    </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <b>Funcionamos todos os dias da semana!! (Que bom, não?) Veja nossos horários:</b>
                        <ul>
                            <li>De Segunda a Sábado: Das 7:00hs as 19:00hs</li>
                            <li>Domingos: Das 7:00hs as 12:00hs</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingTwo">
                    <button class="accordion-button collapsed bg-verde" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        Produtos Fresquinhos
                    </button>
                </h2>
                <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        Para garantir a qualidade de nossos produtos, nossos estoques são repostos <b>todos os dias</b> antes de abrir a nossa loja, assim garantimos que você encontrará produtos fresquinhos por aqui sempre!
                    </div>
              </div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingThree">
                    <button class="accordion-button collapsed bg-verde" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                        Mercearia
                    </button>
                </h2>
                <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        Dispomos de um setor de mercearia que inclui diversos produtos do dia-a-dia para garantir o abastecimento, faltou aquele sal para sua salada? Aqui você encontrará! Compre tudo o que precisa no Portuga's!
                    </div>
                </div>
            </div>
        </div>
        <br><br>

    </div>
{% endblock %}